trigger:
  branches:
    include:
      - main  # Define the branch that triggers the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Use a single hosted agent (no parallelism)

variables:
  - group: api-token

stages:
  - stage: Build
    jobs:
      - job: MavenBuild
        steps:
          - script: |
              sudo apt update
              sudo apt install -y openjdk-11-jdk
              java -version  # Verify installation
            displayName: 'Install Java 11'
          - script: mvn -B clean compile
            displayName: 'Build with Maven'

  - stage: Test
    dependsOn: Build  # Ensures that this stage runs after Build
    jobs:
      - job: MavenTest
        steps:
          - script: mvn -B test
            displayName: 'Run Tests'

  - stage: CodeAnalysis
    dependsOn: Test  # Ensures that this stage runs after Test
    jobs:
      - job: SonarCloudAnalysis
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'srinathselvan'
              projectKey: 'srinathselvan_spring-petclinic'
              projectName: 'spring-petclinic'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'srinathselvan_spring-petclinic'
              cliProjectName: 'spring-petclinic'
              cliProjectVersion: '1.0'
              extraProperties: |
                sonar.organization=srinathselvan
                sonar.projectKey=srinathselvan_spring-petclinic
                sonar.host.url=https://sonarcloud.io
                sonar.login=$(SONAR_TOKEN)
            displayName: 'Prepare SonarCloud Analysis'

          - script: |
              mvn sonar:sonar \
                -Dsonar.organization=srinathselvan \
                -Dsonar.projectKey=srinathselvan_spring-petclinic \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.login=$(SONAR_TOKEN)
            displayName: 'Run SonarCloud Analysis'

  - stage: DependencyScan
    dependsOn: CodeAnalysis  # Ensures that this stage runs after CodeAnalysis
    jobs:
      - job: SnykScan
        steps:
          - script: |
              curl -o- https://raw.githubusercontent.com/snyk/snyk/master/install.sh | bash
              snyk auth $(SNYK_TOKEN)
              snyk test --all-projects
            displayName: 'Run Snyk Dependency Scan'

  - stage: Package
    dependsOn: DependencyScan  # Ensures that this stage runs after DependencyScan
    jobs:
      - job: PackageArtifact
        steps:
          - script: mvn -B package
            displayName: 'Package Application'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/target/*.jar'
              artifactName: 'java-maven-app'
            displayName: 'Publish Artifact'
