apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-ci-cd-app
  template:
    metadata:
      labels:
        app: secure-ci-cd-app
    spec:
      containers:
      - name: secure-ci-cd-app
        image: securecicdregistry.azurecr.io/secure-ci-cd-app:
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: secure-ci-cd-service
spec:
  selector:
    app: secure-ci-cd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

