apiVersion: v1
kind: Service
metadata:
  name: secure-ci-cd-service
spec:
  selector:
    app: secure-ci-cd-app  # Matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 3000 # Internal port where your container is running
  type: LoadBalancer    # Exposes the service externally using a LoadBalancer
